#!/bin/bash
./mvnw clean install
BUILD_DIR=$(./mvnw -q -DforceStdout help:evaluate -Dexpression=project.build.directory)
FINAL_NAME=$(./mvnw -q -DforceStdout help:evaluate -Dexpression=project.build.finalName)
JAR_NAME="${BUILD_DIR}/${FINAL_NAME}.jar"

echo "Path of jar is: ${JAR_NAME}"
java -jar ${JAR_NAME}
